version: 2.1

orbs:
  slack: circleci/slack@4.1

executors:
  my-executor:
    docker:
      - image: hashicorp/terraform:1.1.4
    resource_class: small

commands:
  install-tfnotify:
    steps:
      - run:
        name: "download tfnotify"
        command: "curl -fL -o tfnotify.tar.gz https://github.com/mercari/tfnotify/releases/download/v0.7.0/tfnotify_linux_amd64.tar.gz"
      - run:
        name: "install tfnotify"
        command: "tar -C /usr/bin -xzf ./tfnotify.tar.gz"

jobs:
  say-hello:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - insall-tfnotify
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          context:
            - slack
